/**
 * Domain model of the personal finance app.
 * Monetary values are ALWAYS stored as integer cents (never floats).
 */

export type ISODate = string; // yyyy-MM-dd

export type TransactionType = "expense" | "income";

export type ExpenseStatus = "paid" | "pending";
export type IncomeStatus = "received" | "pending";
export type ChargeStatus = "pending" | "received" | "canceled";

export type Recurrence = "none" | "weekly" | "monthly" | "yearly";

export type PaymentMethodId =
  | "pix"
  | "debit"
  | "credit"
  | "cash"
  | "boleto"
  | "transfer";

export interface PaymentMethod {
  id: PaymentMethodId;
  label: string;
}

export type CategoryKind = "expense" | "income";

export interface Category {
  id: string;
  name: string;
  kind: CategoryKind;
  /** lucide-react icon name used by the CategoryIcon component */
  icon: string;
  /** tailwind classes for the icon chip */
  tone: string;
  /** hex color used by charts */
  color: string;
}

export interface BaseTransaction {
  id: string;
  description: string;
  /** integer cents */
  amount: number;
  date: ISODate;
  categoryId: string;
  notes?: string;
  recurrence: Recurrence;
  createdAt: string;
}

export interface Expense extends BaseTransaction {
  type: "expense";
  status: ExpenseStatus;
  paymentMethod: PaymentMethodId;
  /** due date for pending bills (defaults to date) */
  dueDate?: ISODate;
}

export interface Income extends BaseTransaction {
  type: "income";
  status: IncomeStatus;
  /** set when the income was generated by settling a charge */
  chargeId?: string;
}

export type Transaction = Expense | Income;

export interface Charge {
  id: string;
  clientName: string;
  description: string;
  amount: number;
  dueDate: ISODate;
  status: ChargeStatus;
  receivedAt?: ISODate;
  notes?: string;
  recurrence: Recurrence;
  createdAt: string;
}

export interface FinancialSummary {
  /** received incomes in the period */
  income: number;
  /** all expenses in the period (paid + pending) */
  expenses: number;
  paidExpenses: number;
  /** pending expenses in the period */
  toPay: number;
  /** pending / overdue charges (all-time, they never expire) */
  toReceive: number;
  /** received income - paid expenses (all time, up to end of period) */
  balance: number;
  /** result of the period: income - expenses */
  periodResult: number;
  /** expenses / income ratio, 0..n */
  spendingRatio: number;
}

export type PeriodPreset =
  | "today"
  | "week"
  | "month"
  | "year"
  | "custom";

export interface Period {
  preset: PeriodPreset;
  from: ISODate;
  to: ISODate;
}

export interface ExpenseInput {
  description: string;
  amount: number;
  date: ISODate;
  categoryId: string;
  paymentMethod: PaymentMethodId;
  status: ExpenseStatus;
  notes?: string;
  recurrence: Recurrence;
}

export interface IncomeInput {
  description: string;
  amount: number;
  date: ISODate;
  categoryId: string;
  status: IncomeStatus;
  notes?: string;
  recurrence: Recurrence;
}

export interface ChargeInput {
  clientName: string;
  description: string;
  amount: number;
  dueDate: ISODate;
  notes?: string;
  recurrence: Recurrence;
}
