import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { CreateIncomeDto } from './dto/create-income.dto';
import { UpdateIncomeDto } from './dto/update-income.dto';
import { parseISODate, toISODate } from '../common/date.util';
import { requireCategory } from '../categories/categories.service';

@Injectable()
export class IncomesService {
  constructor(private readonly prisma: PrismaService) {}

  findAll(userId: string) {
    return this.prisma.forUser(userId, (tx) => tx.income.findMany({ where: { userId }, orderBy: { date: 'desc' } }));
  }

  create(userId: string, dto: CreateIncomeDto) {
    return this.prisma.forUser(userId, async (tx) => {
      await requireCategory(tx, userId, dto.categoryId, 'income');
      return tx.income.create({
        data: {
          userId,
          description: dto.description,
          amount: dto.amount,
          date: parseISODate(dto.date),
          categoryId: dto.categoryId,
          status: dto.status,
          notes: dto.notes,
          recurrence: dto.recurrence,
        },
      });
    });
  }

  /** Used only by ChargesService.settle() — an income generated by receiving a charge, never by direct user input. */
  createFromCharge(
    tx: Prisma.TransactionClient,
    userId: string,
    params: { chargeId: string; description: string; amount: number; date: Date; categoryId: string },
  ) {
    return tx.income.create({
      data: {
        userId,
        description: params.description,
        amount: params.amount,
        date: params.date,
        categoryId: params.categoryId,
        status: 'received',
        recurrence: 'none',
        chargeId: params.chargeId,
      },
    });
  }

  async update(userId: string, id: string, dto: UpdateIncomeDto) {
    const result = await this.prisma.forUser(userId, async (tx) => {
      if (dto.categoryId) await requireCategory(tx, userId, dto.categoryId, 'income');
      return tx.income.updateMany({
        where: { id, userId },
        data: {
          description: dto.description,
          amount: dto.amount,
          date: dto.date ? parseISODate(dto.date) : undefined,
          categoryId: dto.categoryId,
          status: dto.status,
          notes: dto.notes,
          recurrence: dto.recurrence,
        },
      });
    });
    if (result.count === 0) throw new NotFoundException('Receita não encontrada.');
    return this.findOne(userId, id);
  }

  async remove(userId: string, id: string) {
    const result = await this.prisma.forUser(userId, (tx) => tx.income.deleteMany({ where: { id, userId } }));
    if (result.count === 0) throw new NotFoundException('Receita não encontrada.');
  }

  private async findOne(userId: string, id: string) {
    const row = await this.prisma.forUser(userId, (tx) => tx.income.findFirst({ where: { id, userId } }));
    if (!row) throw new NotFoundException('Receita não encontrada.');
    return row;
  }
}

export function toIncomeResponse(row: {
  id: string;
  description: string;
  amount: number;
  date: Date;
  categoryId: string;
  status: string;
  chargeId: string | null;
  notes: string | null;
  recurrence: string;
  createdAt: Date;
}) {
  return {
    id: row.id,
    type: 'income' as const,
    description: row.description,
    amount: row.amount,
    date: toISODate(row.date),
    categoryId: row.categoryId,
    status: row.status,
    chargeId: row.chargeId ?? undefined,
    notes: row.notes ?? undefined,
    recurrence: row.recurrence,
    createdAt: row.createdAt.toISOString(),
  };
}
